package com.psf.core.model;

import java.io.Serializable;

public class Raspberry implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raspberry.rid
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column raspberry.address
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raspberry.rid
     *
     * @return the value of raspberry.rid
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raspberry.rid
     *
     * @param rid the value for raspberry.rid
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column raspberry.address
     *
     * @return the value of raspberry.address
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column raspberry.address
     *
     * @param address the value for raspberry.address
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rid=").append(rid);
        sb.append(", address=").append(address);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}