package com.psf.core.mapper;

import com.psf.core.model.Raspberry;
import com.psf.core.model.RaspberryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RaspberryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    long countByExample(RaspberryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int deleteByExample(RaspberryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int deleteByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int insert(Raspberry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int insertSelective(Raspberry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    List<Raspberry> selectByExample(RaspberryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    Raspberry selectByPrimaryKey(String rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Raspberry record, @Param("example") RaspberryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int updateByExample(@Param("record") Raspberry record, @Param("example") RaspberryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int updateByPrimaryKeySelective(Raspberry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table raspberry
     *
     * @mbg.generated Mon Jul 13 15:32:10 CST 2020
     */
    int updateByPrimaryKey(Raspberry record);
}